package com.spin.id.preference.tinyDb

object TinyConstant {
    const val TINY_LIST_GAME = "TINY_LIST_GAME"
    const val TINY_LIST_TOPIC = "TINY_LIST_TOPIC"
    const val TINY_LIST_IMPRESSION = "TINY_LIST_IMPRESSION"

    const val TINY_PROFILE = "TINY_PROFILE"
    const val TINY_STATUS_LOGIN = "TINY_STATUS_LOGIN"
    const val TINY_STATUS_LOGOUT = "TINY_STATUS_LOGOUT"
    const val TINY_USERNAME = "TINY_STATUS_USERNAME"
    const val TINY_PASSWORD = "TINY_STATUS_PASSWORD"
    const val TINY_TOKEN = "TINY_TOKEN"
    const val TINY_CONFIG = "TINY_CONFIG"

    const val TINY_DEEP_LINK = "TINY_DEEP_LINK"
    const val TINY_DEEP_LINK_USER_ID = "TINY_DEEP_LINK_USER_ID"
    const val TINY_DEEP_LINK_PAGE = "TINY_DEEP_LINK_PAGE"
    const val TINY_DEEP_LINK_VALUE = "TINY_DEEP_LINK_VALUE"

    const val TINY_NOTIFICATION = "TINY_NOTIFICATION"

    const val TINY_DATA_COMMENT_LIKE = "TINY_DATA_COMMENT_LIKE"
    const val TINY_DAILY_DATE = "TINY_DAILY_DATE"

    const val TINY_DYNAMIC_CONFIG = "TINY_DYNAMIC_CONFIG"

    const val TINY_LAST_SELECTED_CAPTION = "TINY_LAST_SELECTED_CAPTION"
    const val TINY_LAST_SELECTED_LIST = "TINY_LAST_SELECTED_LIST"

    const val TINY_LAST_SELECTED_PRODUCT_ID = "TINY_LAST_SELECTED_PRODUCT_ID"
    const val TINY_LAST_SELECTED_PRODUCT_NAME = "TINY_LAST_SELECTED_PRODUCT_NAME"
    const val TINY_LAST_SELECTED_ITEM_PRODUCT_ID = "TINY_LAST_SELECTED_ITEM_PRODUCT_ID"

    const val TINY_ORDER_HISTORY = "TINY_ORDER_HISTORY"
}